#include "beep_info.h"

#define BUZZER_PIN  8

int KEY[] = {
    STOP, STOP, STOP, DM6, DM7, DH1, DM7, DH1, DH3, DM7, DM7, DM7, DM3, DM3,
    DM6, DM5, DM6, DH1, DM5, DM5, DM5, DM3, DM4, DM3, DM4, DH1, DM3, DM3,
    STOP, DH1, DH1, DH1, DM7, DM4, DM4, DM7, DM7, DM7, STOP, DM6, DM7, DH1,
    DM7, DH1, DH3, DM7, DM7, DM7, DM3, DM3, DM6, DM5, DM6, DH1, DM5, DM5,
    DM5, DM2, DM3, DM4, DH1, DM7, DM7, DH1, DH1, DH2, DH2, DH3, DH1, DH1,
    DH1, DH1, DM7, DM6, DM6, DM7, DM5, DM6, DM6, DM6, DH1, DH2, DH3, DH2,
    DH3, DH5, DH2, DH2, DH2, DM5, DM5, DH1, DM7, DH1, DH3, DH3, DH3, DH3,
    DH3, DM6, DM7, DH1, DM7, DH2, DH2, DH1, DM5, DM5, DM5, DH4, DH3, DH2,
    DH1, DH3, DH3, DH3, DH3, DH6, DH6, DH5, DH5, DH3, DH2, DH1, DH1, STOP,
    DH1, DH2, DH1, DH2, DH2, DH5, DH3, DH3, DH3, DH3, DH6, DH6, DH5, DH5,
    DH3, DH2, DH1, DH1, STOP, DH1, DH2, DH1, DH2, DH2, DM7, DM6, DM6, DM6,
    DM6, DM7,
};

float LENGTH[] = {
    WHOLE, WHOLE, WHOLE, HALF, HALF, WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE,
    WHOLE, WHOLE, HALF, HALF, WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE,
    WHOLE, WHOLE, WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, HALF, HALF,
    HALF, HALF, WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF,
    HALF, WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF, HALF,
    WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF, HALF, WHOLE,
    HALF, QUARTER, QUARTER, QUARTER, HALF, HALF, HALF, HALF, QUARTER, HALF,
    WHOLE, HALF, HALF, HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF,
    HALF, WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF, HALF,
    WHOLE+HALF, HALF, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF, HALF,
    WHOLE, WHOLE, HALF, HALF, WHOLE+HALF, QUARTER, HALF, WHOLE, WHOLE, WHOLE,
    WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE,
    HALF, HALF, WHOLE, WHOLE, HALF, HALF, WHOLE, HALF, HALF, WHOLE, WHOLE,
    WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, WHOLE, HALF, HALF, WHOLE,
    WHOLE, HALF, HALF, WHOLE, HALF, QUARTER, HALF, WHOLE, WHOLE, WHOLE, WHOLE,
    HALF, HALF
};

void setup() {
    pinMode(BUZZER_PIN, OUTPUT);
}

void loop() {
    delay(1000);
    for (int i = 0; i < sizeof(LENGTH) / sizeof(float); i++) {
        tone(BUZZER_PIN, KEY[i]);
        delay(LENGTH[i] * 400);
        noTone(BUZZER_PIN);
    }
}
